<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stock [
    <!ELEMENT stock (new-car+ | used-car+)>
    <!ELEMENT new-car (model, price)>
    <!ELEMENT used-car (model, price, mileage, condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ATTLIST model name CDATA #REQUIRED>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>

<stock>
    <new-car>
        <model name="Toyota Corolla 2025">Toyota Corolla 2025</model>
        <price>25000</price>
    </new-car>

    <new-car>
        <model>Honda Civic 2025</model>
        <price>27000</price>
    </new-car>

    <used-car>
        <model>Ford Focus 2018</model>
        <price>12000</price>
        <mileage>55000</mileage>
        <condition>Good</condition>
    </used-car>

    <used-car>
        <model>Nissan Sunny 2016</model>
        <price>9500</price>
        <mileage>80000</mileage>
    </used-car>
</stock>
